#########################################################################################
#Folders and Paths REQUIRED
#########################################################################################
workdir: "WORKDIR" #output will be in the results subfolder of the workdir
intervals_of_interest: "/path/to/intervals/intervals_of_interest.bed" #bed file with intervals of interest to subset data

# paths to manifest files
samplemanifest: "WORKDIR/samples.tsv"
contrastmanifest: "WORKDIR/contrasts.tsv"

########################################################################################
#user parameters
#########################################################################################
species: "hg19"

#########################################################################################
# reference files
#########################################################################################
adapters: "/data/CCBR_Pipeliner/ccbr1214/adapters/TruSeq_and_nextera_adapters.fa"