#########################################################################################
#Folders and Paths REQUIRED
#########################################################################################
workdir: "WORKDIR" #output will be in the results subfolder of the workdir

# paths to manifest files
samplemanifest: "WORKDIR/manifests/samples.tsv"

########################################################################################
#user parameters
#########################################################################################
########################
# Required
########################
species: "hg19" #species hg19 or hg38
reference_source: "usc" #NCBI or USC

# first pass completes trimming, alignment, assembly and a complete histogram
# second pass completes subsetting, DAC analysis and DYAD analysis
# third pass completes comparisons between multiple samples
pipeline_phase: "first_pass" #first_pass, second_pass, third_pass

########################
# second_pass required
########################
# User may change the selected-bed file to include a different bed file to subset samples
## file must be located /WORKDIR/resourcs/
bed_list_name: "bed_lists.csv"
## file includes a shorthand_/name,abosulte_path
## example
### selected_shorthand,selected_bed
### NAME_FILL_IN,/data/CCBR_Pipeliner/Pipelines/ccbr1214/bed_files/hg19_protein-coding_genes.bed
### NAME_FILL_IN,/data/CCBR_Pipeliner/Pipelines/ccbr1214/bed_files/1000.Genes.ALU-rich.bed
### NAME_FILL_IN,/data/CCBR_Pipeliner/Pipelines/ccbr1214/bed_files/2500.Genes.ALU-depleted.bed

# if the file has not been created then create it
# grep -Fwf $gene_list $master_bed_file | awk -v OFS='\t' '{{print $1,$2,$3}}'> $selected_bed_file

fragment_length_min: "140" #minimum fragment length
fragment_length_max: "160" #maximum fragment length

limit: 1000000
max_distance: 1500

########################
# third required
########################
# if selected the manifest/contrast_manifest.tsv must be completed
output_contrast_location: "WORKDIR/merged_DACS" #"/data/Zhurkin-20/analysis/sent_to_pi/"
contrastmanifest: "WORKDIR/manifests/CONTRASTS_FILL_IN.tsv"
contrast_shorthand: "SHORTHAND_FILL_IN"

#########################################################################################
# reference files
#########################################################################################
index_dir: "/data/CCBR_Pipeliner/Pipelines/ccbr1214/indices"
adaptors: "/data/CCBR_Pipeliner/Pipelines/ccbr1214/adapters/TruSeq_and_nextera_adapters.fa"
master_bed_file: "/data/CCBR_Pipeliner/Pipelines/ccbr1214/bed_files/hg19_protein-coding_genes.bed" #path to the master bed that will  be used to create a selected_bed, if one is not provided