#########################################################################################
#Folders and Paths REQUIRED
#########################################################################################
workdir: "WORKDIR" #output will be in the results subfolder of the workdir

# paths to manifest files
samplemanifest: "WORKDIR/samples.tsv"
contrastmanifest: "WORKDIR/contrasts.tsv"

########################################################################################
#user parameters
#########################################################################################
species: "hg19"

run_select_bed: "Y" # whether to run pipeline for selected_bed file
intervals_of_interest: "WORKDIR/intervals_of_interest.bed" #bed file with intervals of interest to subset data

#########################################################################################
# reference files
#########################################################################################
adaptors: "/data/CCBR_Pipeliner/ccbr1214/adapters/TruSeq_and_nextera_adapters.fa"